#:schema node_modules/wrangler/config-schema.json
name = "shadcn-admin-react-router"

main = "./server.ts"
workers_dev = true
# https://developers.cloudflare.com/workers/platform/compatibility-dates
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2024-09-26"

# https://developers.cloudflare.com/workers/static-assets/binding/
assets = { directory = "./build/client", binding = 'ASSETS'}

[observability]
enabled = true

#[build]
#command = "pnpm run build"
